# Generated by Django 3.1 on 2026-09-05 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ho', models.CharField(max_length=255, verbose_name='Tên họ')),
                ('thuy_to', models.CharField(blank=True, max_length=255, verbose_name='Thuỷ tổ')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('visibility', models.CharField(choices=[('private', 'Riêng tư'), ('public', 'Công khai')], default='private', max_length=16, verbose_name='Chế độ hiển thị')),
                ('public_slug', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Slug công khai')),
                ('hide_living_details', models.BooleanField(default=True, verbose_name='Ẩn thông tin người còn sống')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Dòng họ',
                'verbose_name_plural': 'Dòng họ',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(db_index=True, max_length=255, verbose_name='Họ tên')),
                ('ten_huy', models.CharField(blank=True, max_length=255, verbose_name='Tên huý')),
                ('ten_tu', models.CharField(blank=True, max_length=255, verbose_name='Tên tự')),
                ('ten_hieu', models.CharField(blank=True, max_length=255, verbose_name='Tên hiệu')),
                ('thuy_hieu', models.CharField(blank=True, max_length=255, verbose_name='Thuỵ hiệu')),
                ('gioi_tinh', models.CharField(choices=[('nam', 'Nam'), ('nu', 'Nữ'), ('khac', 'Khác')], max_length=8, verbose_name='Giới tính')),
                ('parent_kind', models.CharField(choices=[('ruot', 'Ruột'), ('nuoi', 'Nuôi'), ('ke', 'Kế')], default='ruot', max_length=8, verbose_name='Quan hệ với cha mẹ')),
                ('generation', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Đời thứ')),
                ('branch', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Chi/nhánh')),
                ('birth_order', models.IntegerField(blank=True, null=True, verbose_name='Con thứ')),
                ('is_truong', models.BooleanField(default=False, verbose_name='Con trưởng')),
                ('birth_solar', models.DateField(blank=True, null=True, verbose_name='Ngày sinh dương lịch')),
                ('birth_lunar_day', models.IntegerField(blank=True, null=True, verbose_name='Ngày sinh âm lịch')),
                ('birth_lunar_month', models.IntegerField(blank=True, null=True, verbose_name='Tháng sinh âm lịch')),
                ('birth_lunar_leap', models.BooleanField(default=False, verbose_name='Tháng nhuận (sinh)')),
                ('death_solar', models.DateField(blank=True, null=True, verbose_name='Ngày mất dương lịch')),
                ('death_lunar_day', models.IntegerField(blank=True, null=True, verbose_name='Ngày mất âm lịch')),
                ('death_lunar_month', models.IntegerField(blank=True, null=True, verbose_name='Tháng mất âm lịch')),
                ('death_lunar_leap', models.BooleanField(default=False, verbose_name='Tháng nhuận (mất)')),
                ('que_quan', models.CharField(blank=True, max_length=255, verbose_name='Quê quán')),
                ('nghe_nghiep', models.CharField(blank=True, max_length=255, verbose_name='Nghề nghiệp')),
                ('tieu_su', models.TextField(blank=True, verbose_name='Tiểu sử')),
                ('photo_key', models.CharField(blank=True, max_length=255, verbose_name='Khoá ảnh')),
                ('mo_phan_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vĩ độ mộ phần')),
                ('mo_phan_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh độ mộ phần')),
                ('mo_phan_note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú mộ phần')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xoá (mềm)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='giapha.clan', verbose_name='Dòng họ')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='giapha.person', verbose_name='Cha')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='giapha.person', verbose_name='Mẹ')),
            ],
            options={
                'verbose_name': 'Thành viên gia phả',
                'verbose_name_plural': 'Thành viên gia phả',
            },
        ),
        migrations.CreateModel(
            name='PersonRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xoá')], max_length=8, verbose_name='Hành động')),
                ('payload_json', models.TextField(verbose_name='Dữ liệu snapshot (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thao tác')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='giapha.person', verbose_name='Thành viên')),
            ],
            options={
                'verbose_name': 'Lịch sử thay đổi',
                'verbose_name_plural': 'Lịch sử thay đổi',
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Thứ tự')),
                ('status', models.CharField(choices=[('dang_ket_hon', 'Đang kết hôn'), ('ly_hon', 'Ly hôn'), ('goa', 'Goá')], max_length=16, verbose_name='Trạng thái')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('husband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_husband', to='giapha.person', verbose_name='Chồng')),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_wife', to='giapha.person', verbose_name='Vợ')),
            ],
            options={
                'verbose_name': 'Hôn nhân',
                'verbose_name_plural': 'Hôn nhân',
            },
        ),
        migrations.CreateModel(
            name='ClanMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Chủ sở hữu'), ('editor', 'Biên tập viên'), ('viewer', 'Người xem')], max_length=16, verbose_name='Vai trò')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tham gia')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='giapha.clan', verbose_name='Dòng họ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thành viên dòng họ',
                'verbose_name_plural': 'Thành viên dòng họ',
            },
        ),
        migrations.CreateModel(
            name='ClanInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='Mã mời')),
                ('role', models.CharField(choices=[('owner', 'Chủ sở hữu'), ('editor', 'Biên tập viên'), ('viewer', 'Người xem')], default='viewer', max_length=16, verbose_name='Vai trò')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn lúc')),
                ('max_uses', models.IntegerField(default=0, verbose_name='Số lần dùng tối đa')),
                ('used_count', models.IntegerField(default=0, verbose_name='Số lần đã dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='giapha.clan', verbose_name='Dòng họ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Mã mời dòng họ',
                'verbose_name_plural': 'Mã mời dòng họ',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['clan', 'generation'], name='giapha_person_clan_gen_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['clan', 'branch'], name='giapha_person_clan_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['clan', 'death_lunar_month', 'death_lunar_day'], name='giapha_person_clan_gio_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marriage',
            unique_together={('husband', 'wife')},
        ),
        migrations.AlterUniqueTogether(
            name='clanmember',
            unique_together={('clan', 'user')},
        ),
    ]
