# Generated by Django 3.1 on 2026-09-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giapha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Đã xoá (mềm)'),
        ),
    ]
