# Generated by Django 3.1 on 2026-09-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giapha', '0002_clan_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claninvite',
            name='role',
            field=models.CharField(choices=[('editor', 'Biên tập viên'), ('viewer', 'Người xem')], default='viewer', max_length=16, verbose_name='Vai trò'),
        ),
    ]
