# Generated by Django 3.1 on 2026-09-10 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giapha', '0008_drop_social_auth_migration_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Gia phả cá nhân',
                'verbose_name_plural': 'Gia phả cá nhân',
            },
        ),
        migrations.CreateModel(
            name='FamilyPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='Họ tên')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('unknown', 'Chưa rõ')], default='unknown', max_length=8, verbose_name='Giới tính')),
                ('deceased', models.BooleanField(default=False, verbose_name='Đã mất')),
                ('father_rel', models.CharField(blank=True, choices=[('blood', 'Ruột'), ('adopted', 'Nuôi')], max_length=8, null=True, verbose_name='Quan hệ với cha')),
                ('mother_rel', models.CharField(blank=True, choices=[('blood', 'Ruột'), ('adopted', 'Nuôi')], max_length=8, null=True, verbose_name='Quan hệ với mẹ')),
                ('solar_birth_date', models.DateField(blank=True, null=True, verbose_name='Ngày sinh dương')),
                ('birth_time', models.CharField(blank=True, max_length=5, null=True, verbose_name='Giờ sinh (HH:mm)')),
                ('birth_order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự sinh (1 = con cả)')),
                ('solar_death_date', models.DateField(blank=True, null=True, verbose_name='Ngày mất dương (suy ra)')),
                ('death_time', models.CharField(blank=True, max_length=5, null=True, verbose_name='Giờ mất (HH:mm)')),
                ('lunar_death_day', models.IntegerField(blank=True, null=True, verbose_name='Ngày mất âm')),
                ('lunar_death_month', models.IntegerField(blank=True, null=True, verbose_name='Tháng mất âm')),
                ('lunar_death_year', models.IntegerField(blank=True, null=True, verbose_name='Năm mất âm')),
                ('lunar_leap', models.BooleanField(blank=True, null=True, verbose_name='Tháng nhuận')),
                ('relationship', models.CharField(blank=True, max_length=24, null=True, verbose_name='Quan hệ với tôi')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
                ('gio_event_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Id sự kiện giỗ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='giapha.family', verbose_name='Gia phả')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='giapha.familyperson', verbose_name='Cha')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='giapha.familyperson', verbose_name='Mẹ')),
            ],
            options={
                'verbose_name': 'Người trong gia phả cá nhân',
                'verbose_name_plural': 'Người trong gia phả cá nhân',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='self_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='giapha.familyperson', verbose_name='Người là "tôi"'),
        ),
        migrations.AddField(
            model_name='family',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.CreateModel(
            name='FamilySpouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('married', 'Đã kết hôn'), ('divorced', 'Ly hôn')], default='married', max_length=8, verbose_name='Loại')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_links', to='giapha.family', verbose_name='Gia phả')),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_links_a', to='giapha.familyperson', verbose_name='Người A')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_links_b', to='giapha.familyperson', verbose_name='Người B')),
            ],
            options={
                'verbose_name': 'Vợ/chồng (gia phả cá nhân)',
                'verbose_name_plural': 'Vợ/chồng (gia phả cá nhân)',
                'unique_together': {('person_a', 'person_b')},
            },
        ),
    ]
