"""
Django settings for djangopj project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


def env_flag(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


DEBUG = env_flag('DJANGO_DEBUG', False)

# Secrets come from the environment. See .env.example. The previously
# committed key and database password must be treated as compromised and
# rotated -- they remain in the git history.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is off.'
        )
    SECRET_KEY = 'dev-only-insecure-key-not-for-production'

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1' if DEBUG else '')

# Application definition

INSTALLED_APPS = [
    'apis.apps.ApisConfig',
    'giapha.apps.GiaPhaConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_object_actions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CorsMiddleware must precede CommonMiddleware so that CORS headers are
    # attached to the redirects CommonMiddleware can generate. It used to sit
    # after it, and CommonMiddleware was listed twice.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangopj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangopj.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'django-db'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
# `collectstatic` target. Required in production: with DEBUG off Django serves
# no static files at all, so the admin (the CMS surface on
# cms-calendar.thienvanlichphap.vn) renders unstyled unless nginx serves this
# directory at /static/. docker-compose.prod.yml bind-mounts it to the host.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Left permissive because the public almanac endpoints are read-only and
# unauthenticated. Set DJANGO_CORS_ALLOWED_ORIGINS to lock it down.
CORS_ALLOWED_ORIGINS = env_list('DJANGO_CORS_ALLOWED_ORIGINS')
CORS_ALLOW_ALL_ORIGINS = not CORS_ALLOWED_ORIGINS

REST_FRAMEWORK = {
    # A SETTINGS STRING on purpose: DRF resolves it, so `giapha/` still imports
    # nothing from `apis/` (docs/code-standards.md decoupling rule).
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apis.authentication.JWTAuthentication',
    ),
    # No `DEFAULT_THROTTLE_CLASSES` -- deliberate, `apis/` has none and this
    # must not change project-wide. `giapha.views.clan_membership.JoinClanAPIView`
    # opts itself into the 'giapha-join' scope to blunt invite-code brute
    # forcing; `giapha.views.public.ClanPublicTreeAPIView`/
    # `ClanPublicPersonDetailAPIView` opt into 'giapha-public' for the same
    # reason (no-auth means no per-user bucket exists at all otherwise);
    # every other view stays unthrottled.
    #
    # NEITHER RATE IS A HARD GUARANTEE against scraping or brute-forcing --
    # both are PER-IP buckets (DRF's `BaseThrottle.get_ident`), and "per-IP"
    # is only meaningful once `NUM_PROXIES` below matches how many trusted
    # reverse proxies actually sit in front of Django. A single attacker can
    # still exhaust an invite code's 40-bit keyspace across enough distinct
    # source IPs (or a botnet); these rates raise the cost of a
    # single-source attack, they do not remove the underlying keyspace as
    # the only real defence.
    'DEFAULT_THROTTLE_RATES': {
        'giapha-join': '10/hour',
        'giapha-public': '60/hour',
        # Account endpoints (`apis/views/auth_register.py`,
        # `apis/views/auth_password_reset.py`). Same PER-IP caveat as above -- these
        # raise the cost of a single-source attack and nothing more. The
        # binding limit on guessing a reset code is the PER-CODE attempt
        # counter (`PASSWORD_RESET_MAX_ATTEMPTS`), which no amount of IP
        # rotation can get around.
        'auth-register': '10/hour',
        'auth-forgot-password': '5/hour',
        'auth-reset-password': '10/hour',
        'auth-change-password': '10/hour',
        # Login and refresh (`apis/views/auth_login.py`). Unauthenticated, so
        # per-IP, with the NUM_PROXIES caveat above: this raises the cost of
        # single-source credential stuffing and nothing more. The old
        # `/auth/token` had NO limit at all, so this is strictly an improvement.
        'auth-login': '20/hour',
        'auth-refresh': '60/hour',
        # Generic file upload (`apis/views/file_upload.py`). Unauthenticated,
        # so there is no per-user bucket to use instead. Same PER-IP caveat as
        # everything above -- this raises the cost of a single-source flood and
        # nothing more; the images-only allowlist is what actually bounds what
        # a stranger can put in the bucket.
        'file-upload': '20/hour',
    },
    # How many reverse proxies in front of Django are TRUSTED to append to
    # `X-Forwarded-For` (DRF's `BaseThrottle.get_ident`; see
    # https://www.django-rest-framework.org/api-guide/throttling/#how-clients-are-identified).
    # Left unset (DRF default `None`), DRF uses the ENTIRE raw header as the
    # throttle bucket key -- a caller can put ANY string there and pick
    # their own bucket, making both 'giapha-join' and 'giapha-public' above
    # a no-op (proven: 70 requests with a rotating `X-Forwarded-For` value,
    # zero 429s). `0` (this project's current default -- see
    # `.env.example`) means Django is edge-facing and the header is IGNORED
    # entirely, falling back to `REMOTE_ADDR`; set it to the real proxy
    # count once one is confirmed in front (nginx/Cloudflare/etc.) -- too
    # low still lets a client forge a bucket, too high collapses every
    # client behind the same proxy IP into one bucket.
    'NUM_PROXIES': int(os.environ.get('DJANGO_NUM_PROXIES', '0')),
}

# Username/password is the only login flow: `POST /api/auth/login`
# (`apis/views/auth_login.py`) calls `authenticate()` against this backend and
# mints a JWT.
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

# Firebase Cloud Messaging service account (giapha nhắc giỗ + apis nhắc lịch
# hẹn, both through `giapha.services.fcm`). Declared here so
# the value is configurable the same way as everything else and reachable from
# `override_settings`; `giapha.services.fcm_auth` still falls back to the raw
# environment when these are empty. Never commit the JSON itself.
FIREBASE_CREDENTIALS_PATH = os.environ.get('FIREBASE_CREDENTIALS_PATH', '')
FIREBASE_CREDENTIALS_JSON = os.environ.get('FIREBASE_CREDENTIALS_JSON', '')

# Object storage (S3/R2) for gia phả photo uploads (phase 8). Declared here
# for the same reason as the FIREBASE_* pair above: reachable from
# `override_settings`, and `giapha.services.storage` still falls back to the
# raw environment when these are empty. Leaving all five unset is a valid
# deployment state -- the photo endpoints answer 503, nothing else breaks.
S3_ENDPOINT_URL = os.environ.get('S3_ENDPOINT_URL', '')
S3_BUCKET = os.environ.get('S3_BUCKET', '')
S3_ACCESS_KEY_ID = os.environ.get('S3_ACCESS_KEY_ID', '')
S3_SECRET_ACCESS_KEY = os.environ.get('S3_SECRET_ACCESS_KEY', '')
S3_REGION = os.environ.get('S3_REGION', '')

# Outbound email. Only the password-reset OTP uses this today
# (`apis/services/mailer.py`).
#
# The backend is CHOSEN BY WHETHER `EMAIL_HOST` IS SET, rather than being its
# own env var, so that a host with no mail configuration degrades to printing
# the message on stdout instead of raising at send time. That keeps local dev,
# CI and a half-provisioned deploy working: the OTP is still recoverable from
# the log, and no code path has to special-case "email is not set up".
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST
    else 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_flag('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_flag('EMAIL_USE_SSL', False)
# Django has NO default socket timeout for SMTP. Without this, one unreachable
# mail server pins a gunicorn sync worker until the OS gives up -- a handful of
# password-reset requests is then enough to stall the whole API.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@localhost')

# Password-reset OTP policy (`apis/models/password_reset.py`). Short TTL and a
# small attempt cap are the real defence on a 6-digit code -- see the throttle
# note in REST_FRAMEWORK above for why per-IP limits cannot be relied on.
PASSWORD_RESET_CODE_TTL_SECONDS = int(os.environ.get('PASSWORD_RESET_CODE_TTL_SECONDS', '600'))
PASSWORD_RESET_MAX_ATTEMPTS = int(os.environ.get('PASSWORD_RESET_MAX_ATTEMPTS', '5'))

# JWT auth (`apis/services/jwt_tokens.py`, `apis/authentication.py`). A
# DEDICATED signing key so that rotating it logs everyone out WITHOUT
# invalidating the password-reset code hashes, session cookies and everything
# else keyed on SECRET_KEY. Falls back to SECRET_KEY so an existing deployment
# keeps working with no new variable. Rotating the key alone is NOT a full
# logout: surviving `apis_refreshtoken` rows re-mint under the new key -- see
# docs/deployment-guide.md. The algorithm (HS256) is a constant in the service,
# not a setting.
JWT_SIGNING_KEY = os.environ.get('JWT_SIGNING_KEY') or SECRET_KEY
JWT_ACCESS_TOKEN_LIFETIME_SECONDS = int(os.environ.get('JWT_ACCESS_TOKEN_LIFETIME_SECONDS', '3600'))
JWT_REFRESH_TOKEN_LIFETIME_SECONDS = int(os.environ.get('JWT_REFRESH_TOKEN_LIFETIME_SECONDS', '2592000'))

# HTTPS hardening. Off by default because turning SSL redirect on behind a
# proxy that does not forward the scheme causes a redirect loop; switch these
# on per environment once TLS termination is confirmed. See .env.example.
SECURE_SSL_REDIRECT = env_flag('DJANGO_SECURE_SSL_REDIRECT', False)
SESSION_COOKIE_SECURE = env_flag('DJANGO_SECURE_COOKIES', False)
CSRF_COOKIE_SECURE = env_flag('DJANGO_SECURE_COOKIES', False)
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
if env_flag('DJANGO_BEHIND_TLS_PROXY', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Logging: without this, exceptions swallowed by the views' broad `except`
# blocks disappear entirely and every fault looks like a plain 400.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'apis': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Gia phả dòng họ (giapha app): hard cap on persons per clan, guards against
# runaway data entry and keeps admin/report queries bounded.
MAX_CLAN_PERSONS = 5000
# Gia phả cá nhân (`/v1/family`): every request loads the caller's whole tree
# (spec: a real family is < 500 people), so the cap bounds that load.
FAMILY_MAX_PERSONS = 1000
