# Generated by Django 3.1 on 2023-03-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiepKy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('lunar_day', models.CharField(max_length=255)),
                ('good_stars', models.TextField(blank=True, null=True)),
                ('ugly_stars', models.TextField(blank=True, null=True)),
                ('should_things', models.TextField(blank=True, null=True)),
                ('no_should_things', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hiep_ky',
            },
        ),
        migrations.CreateModel(
            name='TietKhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiet_khi', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('year', models.CharField(max_length=255)),
                ('gio_soc', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tiet_khi',
            },
        ),
    ]
