# Generated by Django 3.1 on 2023-03-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourInDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunar_day', models.CharField(max_length=255)),
                ('hour_1', models.TextField(blank=True, null=True)),
                ('hour_2', models.TextField(blank=True, null=True)),
                ('hour_3', models.TextField(blank=True, null=True)),
                ('hour_4', models.TextField(blank=True, null=True)),
                ('hour_5', models.TextField(blank=True, null=True)),
                ('hour_6', models.TextField(blank=True, null=True)),
                ('hour_7', models.TextField(blank=True, null=True)),
                ('hour_8', models.TextField(blank=True, null=True)),
                ('hour_9', models.TextField(blank=True, null=True)),
                ('hour_10', models.TextField(blank=True, null=True)),
                ('hour_11', models.TextField(blank=True, null=True)),
                ('hour_12', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hour_in_days',
            },
        ),
    ]
