# Generated by Django 3.1 on 2023-03-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_hourinday'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuyNhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_ngay', models.CharField(max_length=255)),
                ('tiet_khi', models.CharField(max_length=255)),
                ('hour', models.CharField(max_length=255)),
                ('am_duong', models.CharField(max_length=255)),
                ('quy_nhan', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'quy_nhan',
            },
        ),
    ]
