# Generated by Django 3.1 on 2023-03-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20230308_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaiSonHoangDao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tham_lang', models.CharField(blank=True, max_length=255, null=True)),
                ('cu_mon', models.CharField(blank=True, max_length=255, null=True)),
                ('vu_khuc', models.CharField(blank=True, max_length=255, null=True)),
                ('van_khuc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cai_son_hoang_dao',
            },
        ),
        migrations.CreateModel(
            name='KhaiSonHung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nien_khac_son_gia', models.CharField(blank=True, max_length=255, null=True)),
                ('am_phu_thai_tue', models.CharField(blank=True, max_length=255, null=True)),
                ('luc_hai', models.CharField(blank=True, max_length=255, null=True)),
                ('tu_phu', models.CharField(blank=True, max_length=255, null=True)),
                ('cuu_thoai', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'khai_son_hung',
            },
        ),
        migrations.CreateModel(
            name='KhaiSonHungThang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('star_name', models.CharField(blank=True, max_length=255, null=True)),
                ('month_1', models.CharField(blank=True, max_length=255, null=True)),
                ('month_2', models.CharField(blank=True, max_length=255, null=True)),
                ('month_3', models.CharField(blank=True, max_length=255, null=True)),
                ('month_4', models.CharField(blank=True, max_length=255, null=True)),
                ('month_5', models.CharField(blank=True, max_length=255, null=True)),
                ('month_6', models.CharField(blank=True, max_length=255, null=True)),
                ('month_7', models.CharField(blank=True, max_length=255, null=True)),
                ('month_8', models.CharField(blank=True, max_length=255, null=True)),
                ('month_9', models.CharField(blank=True, max_length=255, null=True)),
                ('month_10', models.CharField(blank=True, max_length=255, null=True)),
                ('month_11', models.CharField(blank=True, max_length=255, null=True)),
                ('month_12', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'khai_son_hung_thang',
            },
        ),
        migrations.CreateModel(
            name='KhaiSonTuPhuongCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('star_name', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'khai_son_tu_phuong_cat',
            },
        ),
        migrations.CreateModel(
            name='KhaiSonTuPhuongHung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('thai_tue', models.CharField(blank=True, max_length=255, null=True)),
                ('tue_pha', models.CharField(blank=True, max_length=255, null=True)),
                ('tam_sat', models.CharField(blank=True, max_length=255, null=True)),
                ('toa_sat_huong_sat', models.CharField(blank=True, max_length=255, null=True)),
                ('phu_thien_khong_vong', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'khai_son_tu_phuong_hung',
            },
        ),
        migrations.CreateModel(
            name='LapHuongHung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tuan_son_la_hau', models.CharField(blank=True, max_length=255, null=True)),
                ('benh_phu', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'lap_huong_hung',
            },
        ),
        migrations.CreateModel(
            name='LapHuongHungThang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('star_name', models.CharField(blank=True, max_length=255, null=True)),
                ('month_1', models.CharField(blank=True, max_length=255, null=True)),
                ('month_2', models.CharField(blank=True, max_length=255, null=True)),
                ('month_3', models.CharField(blank=True, max_length=255, null=True)),
                ('month_4', models.CharField(blank=True, max_length=255, null=True)),
                ('month_5', models.CharField(blank=True, max_length=255, null=True)),
                ('month_6', models.CharField(blank=True, max_length=255, null=True)),
                ('month_7', models.CharField(blank=True, max_length=255, null=True)),
                ('month_8', models.CharField(blank=True, max_length=255, null=True)),
                ('month_9', models.CharField(blank=True, max_length=255, null=True)),
                ('month_10', models.CharField(blank=True, max_length=255, null=True)),
                ('month_11', models.CharField(blank=True, max_length=255, null=True)),
                ('month_12', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'lap_huong_hung_thang',
            },
        ),
        migrations.CreateModel(
            name='TamNguyenTuBach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nguyen', models.CharField(blank=True, max_length=255, null=True)),
                ('bach_1', models.CharField(blank=True, max_length=255, null=True)),
                ('bach_6', models.CharField(blank=True, max_length=255, null=True)),
                ('bach_8', models.CharField(blank=True, max_length=255, null=True)),
                ('tu_9', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tam_nguyen_tu_bach',
            },
        ),
        migrations.CreateModel(
            name='TauMaLucNham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('than_hau', models.CharField(blank=True, max_length=255, null=True)),
                ('cong_tao', models.CharField(blank=True, max_length=255, null=True)),
                ('thien_cuong', models.CharField(blank=True, max_length=255, null=True)),
                ('thang_quang', models.CharField(blank=True, max_length=255, null=True)),
                ('truyen_tong', models.CharField(blank=True, max_length=255, null=True)),
                ('ha_khoi', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tau_ma_luc_nham',
            },
        ),
        migrations.CreateModel(
            name='ThongThienKhieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('truoc_phuong_tam_hop', models.CharField(blank=True, max_length=255, null=True)),
                ('sau_phuong_tam_hop', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'thong_thien_khieu',
            },
        ),
        migrations.CreateModel(
            name='TuPhuongHung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('thien_quan_phu', models.CharField(blank=True, max_length=255, null=True)),
                ('dai_tuong_quan', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_quan_phu', models.CharField(blank=True, max_length=255, null=True)),
                ('luc_si', models.CharField(blank=True, max_length=255, null=True)),
                ('tam_that', models.CharField(blank=True, max_length=255, null=True)),
                ('tam_menh', models.CharField(blank=True, max_length=255, null=True)),
                ('tue_hinh', models.CharField(blank=True, max_length=255, null=True)),
                ('hoang_phan', models.CharField(blank=True, max_length=255, null=True)),
                ('phi_liem', models.CharField(blank=True, max_length=255, null=True)),
                ('tang_mon', models.CharField(blank=True, max_length=255, null=True)),
                ('tam_quan', models.CharField(blank=True, max_length=255, null=True)),
                ('dieu_khach', models.CharField(blank=True, max_length=255, null=True)),
                ('kim_than', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_hoa', models.CharField(blank=True, max_length=255, null=True)),
                ('pha_bai_ngu_qui', models.CharField(blank=True, max_length=255, null=True)),
                ('dai_sat', models.CharField(blank=True, max_length=255, null=True)),
                ('bach_ho', models.CharField(blank=True, max_length=255, null=True)),
                ('ngu_qui', models.CharField(blank=True, max_length=255, null=True)),
                ('cau_vi', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tu_phuong_hung',
            },
        ),
        migrations.CreateModel(
            name='TuPhuongHungThang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('star_name', models.CharField(blank=True, max_length=255, null=True)),
                ('month_1', models.CharField(blank=True, max_length=255, null=True)),
                ('month_2', models.CharField(blank=True, max_length=255, null=True)),
                ('month_3', models.CharField(blank=True, max_length=255, null=True)),
                ('month_4', models.CharField(blank=True, max_length=255, null=True)),
                ('month_5', models.CharField(blank=True, max_length=255, null=True)),
                ('month_6', models.CharField(blank=True, max_length=255, null=True)),
                ('month_7', models.CharField(blank=True, max_length=255, null=True)),
                ('month_8', models.CharField(blank=True, max_length=255, null=True)),
                ('month_9', models.CharField(blank=True, max_length=255, null=True)),
                ('month_10', models.CharField(blank=True, max_length=255, null=True)),
                ('month_11', models.CharField(blank=True, max_length=255, null=True)),
                ('month_12', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tu_phuong_hung_thang',
            },
        ),
    ]
