# Generated by Django 3.1 on 2023-03-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_caisonhoangdao_khaisonhung_khaisonhungthang_khaisontuphuongcat_khaisontuphuonghung_laphuonghung_laph'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamKyThang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tam_ky', models.CharField(blank=True, max_length=255, null=True)),
                ('month_1', models.CharField(blank=True, max_length=255, null=True)),
                ('month_2', models.CharField(blank=True, max_length=255, null=True)),
                ('month_3', models.CharField(blank=True, max_length=255, null=True)),
                ('month_4', models.CharField(blank=True, max_length=255, null=True)),
                ('month_5', models.CharField(blank=True, max_length=255, null=True)),
                ('month_6', models.CharField(blank=True, max_length=255, null=True)),
                ('month_7', models.CharField(blank=True, max_length=255, null=True)),
                ('month_8', models.CharField(blank=True, max_length=255, null=True)),
                ('month_9', models.CharField(blank=True, max_length=255, null=True)),
                ('month_10', models.CharField(blank=True, max_length=255, null=True)),
                ('month_11', models.CharField(blank=True, max_length=255, null=True)),
                ('month_12', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tam_ky_thang',
            },
        ),
        migrations.AddField(
            model_name='taumalucnham',
            name='long_duc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taumalucnham',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taumalucnham',
            name='phuc_duc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taumalucnham',
            name='thai_am',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taumalucnham',
            name='thai_duong',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thongthienkhieu',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
