# Generated by Django 3.1 on 2023-03-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20230316_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmPhuThaiTue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('am_phu_thai_tue', models.CharField(blank=True, max_length=255, null=True)),
                ('luc_hai', models.CharField(blank=True, max_length=255, null=True)),
                ('tu_phu', models.CharField(blank=True, max_length=255, null=True)),
                ('cuu_thoai', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'am_phu_thai_tue',
            },
        ),
        migrations.CreateModel(
            name='TuLoiTamNguyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('thai_duong', models.CharField(blank=True, max_length=255, null=True)),
                ('thai_am', models.CharField(blank=True, max_length=255, null=True)),
                ('long_duc', models.CharField(blank=True, max_length=255, null=True)),
                ('phuc_duc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tu_loi_tam_nguyen',
            },
        ),
        migrations.RemoveField(
            model_name='taumalucnham',
            name='long_duc',
        ),
        migrations.RemoveField(
            model_name='taumalucnham',
            name='phuc_duc',
        ),
        migrations.RemoveField(
            model_name='taumalucnham',
            name='thai_am',
        ),
        migrations.RemoveField(
            model_name='taumalucnham',
            name='thai_duong',
        ),
    ]
