# Generated by Django 3.1 on 2023-03-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20230317_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuphuonghung',
            name='phi_vien',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tuphuonghung',
            name='tu_phu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
