# Generated by Django 3.1 on 2023-03-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_sao_saohiepky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sao',
            name='property',
            field=models.TextField(),
        ),
    ]
