# Generated by Django 3.1 on 2023-03-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20230323_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaoHour9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.hourinday')),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
        ),
        migrations.CreateModel(
            name='SaoHour8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.hourinday')),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
        ),
        migrations.CreateModel(
            name='SaoHour7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.hourinday')),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
        ),
        migrations.CreateModel(
            name='SaoHour6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.hourinday')),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
        ),
        migrations.CreateModel(
            name='SaoHour5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.hourinday')),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
        ),
        migrations.CreateModel(
            name='SaoHour4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.hourinday')),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
        ),
        migrations.CreateModel(
            name='SaoHour3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.hourinday')),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
        ),
        migrations.CreateModel(
            name='SaoHour2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.hourinday')),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
        ),
        migrations.CreateModel(
            name='SaoHour12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.hourinday')),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
        ),
        migrations.CreateModel(
            name='SaoHour11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.hourinday')),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
        ),
        migrations.CreateModel(
            name='SaoHour10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.hourinday')),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
        ),
        migrations.CreateModel(
            name='SaoHour1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.hourinday')),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
        ),
    ]
