# Generated by Django 3.1 on 2023-03-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_saohour1_saohour10_saohour11_saohour12_saohour2_saohour3_saohour4_saohour5_saohour6_saohour7_saohour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanSatByMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('month_1', models.CharField(blank=True, max_length=255, null=True)),
                ('month_2', models.CharField(blank=True, max_length=255, null=True)),
                ('month_3', models.CharField(blank=True, max_length=255, null=True)),
                ('month_4', models.CharField(blank=True, max_length=255, null=True)),
                ('month_5', models.CharField(blank=True, max_length=255, null=True)),
                ('month_6', models.CharField(blank=True, max_length=255, null=True)),
                ('month_7', models.CharField(blank=True, max_length=255, null=True)),
                ('month_8', models.CharField(blank=True, max_length=255, null=True)),
                ('month_9', models.CharField(blank=True, max_length=255, null=True)),
                ('month_10', models.CharField(blank=True, max_length=255, null=True)),
                ('month_11', models.CharField(blank=True, max_length=255, null=True)),
                ('month_12', models.CharField(blank=True, max_length=255, null=True)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
            options={
                'db_table': 'than_sat_by_month',
            },
        ),
    ]
