# Generated by Django 3.1 on 2023-04-02 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_thansatbymonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuDaiCatThoiOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=255)),
                ('can_ngay_1', models.CharField(max_length=255, null=True)),
                ('can_ngay_2', models.CharField(max_length=255, null=True)),
                ('can_ngay_3', models.CharField(max_length=255, null=True)),
                ('can_ngay_4', models.CharField(max_length=255, null=True)),
                ('can_ngay_5', models.CharField(max_length=255, null=True)),
                ('can_ngay_6', models.CharField(max_length=255, null=True)),
                ('can_ngay_7', models.CharField(max_length=255, null=True)),
                ('can_ngay_8', models.CharField(max_length=255, null=True)),
                ('can_ngay_9', models.CharField(max_length=255, null=True)),
                ('can_ngay_10', models.CharField(max_length=255, null=True)),
                ('tiet_khi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tu_dai_cat_thoi_old',
            },
        ),
        migrations.RenameField(
            model_name='tudaicatthoi',
            old_name='can_ngay_1',
            new_name='can_ngay',
        ),
        migrations.RemoveField(
            model_name='tudaicatthoi',
            name='can_ngay_10',
        ),
        migrations.RemoveField(
            model_name='tudaicatthoi',
            name='can_ngay_2',
        ),
        migrations.RemoveField(
            model_name='tudaicatthoi',
            name='can_ngay_3',
        ),
        migrations.RemoveField(
            model_name='tudaicatthoi',
            name='can_ngay_4',
        ),
        migrations.RemoveField(
            model_name='tudaicatthoi',
            name='can_ngay_5',
        ),
        migrations.RemoveField(
            model_name='tudaicatthoi',
            name='can_ngay_6',
        ),
        migrations.RemoveField(
            model_name='tudaicatthoi',
            name='can_ngay_7',
        ),
        migrations.RemoveField(
            model_name='tudaicatthoi',
            name='can_ngay_8',
        ),
        migrations.RemoveField(
            model_name='tudaicatthoi',
            name='can_ngay_9',
        ),
        migrations.CreateModel(
            name='TuDaiCatThoiSao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('tudaicatthoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.tudaicatthoi')),
            ],
        ),
    ]
