# Generated by Django 3.1 on 2023-04-02 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_auto_20230402_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanSatByYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
            ],
            options={
                'db_table': 'than_sat_by_year',
            },
        ),
    ]
