# Generated by Django 3.1 on 2023-04-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_auto_20230406_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourinday',
            options={'verbose_name': 'Giờ trong ngày', 'verbose_name_plural': 'Giờ trong ngày'},
        ),
        migrations.AlterModelOptions(
            name='sao',
            options={'verbose_name': 'Sao', 'verbose_name_plural': 'Sao'},
        ),
        migrations.AlterField(
            model_name='hiepky',
            name='lunar_day',
            field=models.CharField(choices=[('GIÁP TÝ', 'GIÁP TÝ'), ('ẤT SỬU', 'ẤT SỬU'), ('BÍNH DẦN', 'BÍNH DẦN'), ('ĐINH MÃO', 'ĐINH MÃO'), ('MẬU THÌN', 'MẬU THÌN'), ('KỶ TỴ', 'KỶ TỴ'), ('CANH NGỌ', 'CANH NGỌ'), ('TÂN MÙI', 'TÂN MÙI'), ('NHÂM THÂN', 'NHÂM THÂN'), ('QUÝ DẬU', 'QUÝ DẬU'), ('GIÁP TUẤT', 'GIÁP TUẤT'), ('ẤT HỢI', 'ẤT HỢI'), ('BÍNH TÝ', 'BÍNH TÝ'), ('ĐINH SỬU', 'ĐINH SỬU'), ('MẬU DẦN', 'MẬU DẦN'), ('KỶ MÃO', 'KỶ MÃO'), ('CANH THÌN', 'CANH THÌN'), ('TÂN TỴ', 'TÂN TỴ'), ('NHÂM NGỌ', 'NHÂM NGỌ'), ('QUÝ MÙI', 'QUÝ MÙI'), ('GIÁP THÂN', 'GIÁP THÂN'), ('ẤT DẬU', 'ẤT DẬU'), ('BÍNH TUẤT', 'BÍNH TUẤT'), ('ĐINH HỢI', 'ĐINH HỢI'), ('MẬU TÝ', 'MẬU TÝ'), ('KỶ SỬU', 'KỶ SỬU'), ('CANH DẦN', 'CANH DẦN'), ('TÂN MÃO', 'TÂN MÃO'), ('NHÂM THÌN', 'NHÂM THÌN'), ('QUÝ TỴ', 'QUÝ TỴ'), ('GIÁP NGỌ', 'GIÁP NGỌ'), ('ẤT MÙI', 'ẤT MÙI'), ('BÍNH THÂN', 'BÍNH THÂN'), ('ĐINH DẬU', 'ĐINH DẬU'), ('MẬU TUẤT', 'MẬU TUẤT'), ('KỶ HỢI', 'KỶ HỢI'), ('CANH TÝ', 'CANH TÝ'), ('TÂN SỬU', 'TÂN SỬU'), ('NHÂM DẦN', 'NHÂM DẦN'), ('QUÝ MÃO', 'QUÝ MÃO'), ('GIÁP THÌN', 'GIÁP THÌN'), ('ẤT TỴ', 'ẤT TỴ'), ('BÍNH NGỌ', 'BÍNH NGỌ'), ('ĐINH MÙI', 'ĐINH MÙI'), ('MẬU THÂN', 'MẬU THÂN'), ('KỶ DẬU', 'KỶ DẬU'), ('CANH TUẤT', 'CANH TUẤT'), ('TÂN HỢI', 'TÂN HỢI'), ('NHÂM TÝ', 'NHÂM TÝ'), ('QUÝ SỬU', 'QUÝ SỬU'), ('GIÁP DẦN', 'GIÁP DẦN'), ('ẤT MÃO', 'ẤT MÃO'), ('BÍNH THÌN', 'BÍNH THÌN'), ('ĐINH TỴ', 'ĐINH TỴ'), ('MẬU NGỌ', 'MẬU NGỌ'), ('KỶ MÙI', 'KỶ MÙI'), ('CANH THÂN', 'CANH THÂN'), ('TÂN DẬU', 'TÂN DẬU'), ('NHÂM TUẤT', 'NHÂM TUẤT'), ('QUÝ HỢI', 'QUÝ HỢI')], max_length=255, verbose_name='Ngày can chi'),
        ),
        migrations.RemoveField(
            model_name='hourinday',
            name='hour_1',
        ),
        migrations.AddField(
            model_name='hourinday',
            name='hour_1',
            field=models.ManyToManyField(related_name='hour_1', through='apis.SaoHour1', to='apis.Sao'),
        ),
        migrations.RemoveField(
            model_name='hourinday',
            name='hour_10',
        ),
        migrations.AddField(
            model_name='hourinday',
            name='hour_10',
            field=models.ManyToManyField(related_name='hour_10', through='apis.SaoHour10', to='apis.Sao'),
        ),
        migrations.RemoveField(
            model_name='hourinday',
            name='hour_11',
        ),
        migrations.AddField(
            model_name='hourinday',
            name='hour_11',
            field=models.ManyToManyField(related_name='hour_11', through='apis.SaoHour11', to='apis.Sao'),
        ),
        migrations.RemoveField(
            model_name='hourinday',
            name='hour_12',
        ),
        migrations.AddField(
            model_name='hourinday',
            name='hour_12',
            field=models.ManyToManyField(related_name='hour_12', through='apis.SaoHour12', to='apis.Sao'),
        ),
        migrations.RemoveField(
            model_name='hourinday',
            name='hour_2',
        ),
        migrations.AddField(
            model_name='hourinday',
            name='hour_2',
            field=models.ManyToManyField(related_name='hour_2', through='apis.SaoHour2', to='apis.Sao'),
        ),
        migrations.RemoveField(
            model_name='hourinday',
            name='hour_3',
        ),
        migrations.AddField(
            model_name='hourinday',
            name='hour_3',
            field=models.ManyToManyField(related_name='hour_3', through='apis.SaoHour3', to='apis.Sao'),
        ),
        migrations.RemoveField(
            model_name='hourinday',
            name='hour_4',
        ),
        migrations.AddField(
            model_name='hourinday',
            name='hour_4',
            field=models.ManyToManyField(related_name='hour_4', through='apis.SaoHour4', to='apis.Sao'),
        ),
        migrations.RemoveField(
            model_name='hourinday',
            name='hour_5',
        ),
        migrations.AddField(
            model_name='hourinday',
            name='hour_5',
            field=models.ManyToManyField(related_name='hour_5', through='apis.SaoHour5', to='apis.Sao'),
        ),
        migrations.RemoveField(
            model_name='hourinday',
            name='hour_6',
        ),
        migrations.AddField(
            model_name='hourinday',
            name='hour_6',
            field=models.ManyToManyField(related_name='hour_6', through='apis.SaoHour6', to='apis.Sao'),
        ),
        migrations.RemoveField(
            model_name='hourinday',
            name='hour_7',
        ),
        migrations.AddField(
            model_name='hourinday',
            name='hour_7',
            field=models.ManyToManyField(related_name='hour_7', through='apis.SaoHour7', to='apis.Sao'),
        ),
        migrations.RemoveField(
            model_name='hourinday',
            name='hour_8',
        ),
        migrations.AddField(
            model_name='hourinday',
            name='hour_8',
            field=models.ManyToManyField(related_name='hour_8', through='apis.SaoHour8', to='apis.Sao'),
        ),
        migrations.RemoveField(
            model_name='hourinday',
            name='hour_9',
        ),
        migrations.AddField(
            model_name='hourinday',
            name='hour_9',
            field=models.ManyToManyField(related_name='hour_9', through='apis.SaoHour9', to='apis.Sao'),
        ),
        migrations.AlterField(
            model_name='hourinday',
            name='lunar_day',
            field=models.CharField(choices=[('GIÁP TÝ', 'GIÁP TÝ'), ('ẤT SỬU', 'ẤT SỬU'), ('BÍNH DẦN', 'BÍNH DẦN'), ('ĐINH MÃO', 'ĐINH MÃO'), ('MẬU THÌN', 'MẬU THÌN'), ('KỶ TỴ', 'KỶ TỴ'), ('CANH NGỌ', 'CANH NGỌ'), ('TÂN MÙI', 'TÂN MÙI'), ('NHÂM THÂN', 'NHÂM THÂN'), ('QUÝ DẬU', 'QUÝ DẬU'), ('GIÁP TUẤT', 'GIÁP TUẤT'), ('ẤT HỢI', 'ẤT HỢI'), ('BÍNH TÝ', 'BÍNH TÝ'), ('ĐINH SỬU', 'ĐINH SỬU'), ('MẬU DẦN', 'MẬU DẦN'), ('KỶ MÃO', 'KỶ MÃO'), ('CANH THÌN', 'CANH THÌN'), ('TÂN TỴ', 'TÂN TỴ'), ('NHÂM NGỌ', 'NHÂM NGỌ'), ('QUÝ MÙI', 'QUÝ MÙI'), ('GIÁP THÂN', 'GIÁP THÂN'), ('ẤT DẬU', 'ẤT DẬU'), ('BÍNH TUẤT', 'BÍNH TUẤT'), ('ĐINH HỢI', 'ĐINH HỢI'), ('MẬU TÝ', 'MẬU TÝ'), ('KỶ SỬU', 'KỶ SỬU'), ('CANH DẦN', 'CANH DẦN'), ('TÂN MÃO', 'TÂN MÃO'), ('NHÂM THÌN', 'NHÂM THÌN'), ('QUÝ TỴ', 'QUÝ TỴ'), ('GIÁP NGỌ', 'GIÁP NGỌ'), ('ẤT MÙI', 'ẤT MÙI'), ('BÍNH THÂN', 'BÍNH THÂN'), ('ĐINH DẬU', 'ĐINH DẬU'), ('MẬU TUẤT', 'MẬU TUẤT'), ('KỶ HỢI', 'KỶ HỢI'), ('CANH TÝ', 'CANH TÝ'), ('TÂN SỬU', 'TÂN SỬU'), ('NHÂM DẦN', 'NHÂM DẦN'), ('QUÝ MÃO', 'QUÝ MÃO'), ('GIÁP THÌN', 'GIÁP THÌN'), ('ẤT TỴ', 'ẤT TỴ'), ('BÍNH NGỌ', 'BÍNH NGỌ'), ('ĐINH MÙI', 'ĐINH MÙI'), ('MẬU THÂN', 'MẬU THÂN'), ('KỶ DẬU', 'KỶ DẬU'), ('CANH TUẤT', 'CANH TUẤT'), ('TÂN HỢI', 'TÂN HỢI'), ('NHÂM TÝ', 'NHÂM TÝ'), ('QUÝ SỬU', 'QUÝ SỬU'), ('GIÁP DẦN', 'GIÁP DẦN'), ('ẤT MÃO', 'ẤT MÃO'), ('BÍNH THÌN', 'BÍNH THÌN'), ('ĐINH TỴ', 'ĐINH TỴ'), ('MẬU NGỌ', 'MẬU NGỌ'), ('KỶ MÙI', 'KỶ MÙI'), ('CANH THÂN', 'CANH THÂN'), ('TÂN DẬU', 'TÂN DẬU'), ('NHÂM TUẤT', 'NHÂM TUẤT'), ('QUÝ HỢI', 'QUÝ HỢI')], max_length=255, verbose_name='Ngày can chi'),
        ),
    ]
