# Generated by Django 3.1 on 2023-04-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_auto_20230407_2036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saohour3',
            unique_together={('hour_3', 'sao')},
        ),
    ]
