# Generated by Django 3.1 on 2023-04-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_auto_20230407_2037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saohour6',
            unique_together={('hour_6', 'sao')},
        ),
    ]
