# Generated by Django 3.1 on 2023-04-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0025_auto_20230407_2037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saohour8',
            unique_together={('hour_8', 'sao')},
        ),
    ]
