# Generated by Django 3.1 on 2023-04-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0026_auto_20230407_2045'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saohour10',
            unique_together={('hour_10', 'sao')},
        ),
        migrations.AlterUniqueTogether(
            name='saohour11',
            unique_together={('hour_11', 'sao')},
        ),
        migrations.AlterUniqueTogether(
            name='saohour12',
            unique_together={('hour_12', 'sao')},
        ),
    ]
