# Generated by Django 3.1 on 2023-04-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0027_auto_20230407_2048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saohour9',
            unique_together={('hour_9', 'sao')},
        ),
    ]
