# Generated by Django 3.1 on 2023-04-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0029_auto_20230407_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiepky',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
