# Generated by Django 3.1 on 2023-04-14 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0030_auto_20230414_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saohiepky',
            name='hiepky',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.hiepky', verbose_name='Ngày'),
        ),
    ]
