# Generated by Django 3.1 on 2023-04-19 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0033_auto_20230414_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thansatbymonth',
            options={'verbose_name': 'Thần sát theo tháng', 'verbose_name_plural': 'Thần sát theo tháng'},
        ),
        migrations.AlterModelOptions(
            name='thansatbyyear',
            options={'verbose_name': 'Thần sát theo năm', 'verbose_name_plural': 'Thần sát theo năm'},
        ),
        migrations.RemoveField(
            model_name='thansatbyyear',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='thansatbyyear',
            name='sao',
        ),
        migrations.CreateModel(
            name='ThanSatByYearSao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cung_son', models.IntegerField(choices=[(1, 'Cung'), (2, 'Son')])),
                ('direction', models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('than_sat_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbyyear')),
            ],
            options={
                'db_table': 'than_sat_by_year_sao',
            },
        ),
        migrations.AddField(
            model_name='thansatbyyear',
            name='sao',
            field=models.ManyToManyField(through='apis.ThanSatByYearSao', to='apis.Sao'),
        ),
    ]
