# Generated by Django 3.1 on 2023-04-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0034_auto_20230419_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thansatbyyearsao',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='thansatbyyearsao',
            name='year',
        ),
    ]
