# Generated by Django 3.1 on 2023-04-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0035_auto_20230419_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmPhuThaiTue',
        ),
        migrations.DeleteModel(
            name='CaiSonHoangDao',
        ),
        migrations.DeleteModel(
            name='KhaiSonHung',
        ),
        migrations.DeleteModel(
            name='KhaiSonHungThang',
        ),
        migrations.DeleteModel(
            name='KhaiSonTuPhuongCat',
        ),
        migrations.DeleteModel(
            name='KhaiSonTuPhuongHung',
        ),
        migrations.DeleteModel(
            name='LapHuongHung',
        ),
        migrations.DeleteModel(
            name='LapHuongHungThang',
        ),
        migrations.DeleteModel(
            name='TamKyThang',
        ),
        migrations.DeleteModel(
            name='TamNguyenTuBach',
        ),
        migrations.DeleteModel(
            name='TauMaLucNham',
        ),
        migrations.DeleteModel(
            name='ThongThienKhieu',
        ),
        migrations.DeleteModel(
            name='TuLoiTamNguyen',
        ),
        migrations.DeleteModel(
            name='TuPhuongHung',
        ),
        migrations.DeleteModel(
            name='TuPhuongHungThang',
        ),
        migrations.AlterModelOptions(
            name='thansatbyyearsao',
            options={'verbose_name': 'Sao', 'verbose_name_plural': 'Sao'},
        ),
        migrations.AlterField(
            model_name='thansatbymonth',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='thansatbyyear',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
