# Generated by Django 3.1 on 2023-04-19 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0036_auto_20230419_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thansatbymonth',
            name='sao',
        ),
        migrations.RemoveField(
            model_name='thansatbymonth',
            name='month_1',
        ),
        migrations.RemoveField(
            model_name='thansatbymonth',
            name='month_10',
        ),
        migrations.RemoveField(
            model_name='thansatbymonth',
            name='month_11',
        ),
        migrations.RemoveField(
            model_name='thansatbymonth',
            name='month_12',
        ),
        migrations.RemoveField(
            model_name='thansatbymonth',
            name='month_2',
        ),
        migrations.RemoveField(
            model_name='thansatbymonth',
            name='month_3',
        ),
        migrations.RemoveField(
            model_name='thansatbymonth',
            name='month_4',
        ),
        migrations.RemoveField(
            model_name='thansatbymonth',
            name='month_5',
        ),
        migrations.RemoveField(
            model_name='thansatbymonth',
            name='month_6',
        ),
        migrations.RemoveField(
            model_name='thansatbymonth',
            name='month_7',
        ),
        migrations.RemoveField(
            model_name='thansatbymonth',
            name='month_8',
        ),
        migrations.RemoveField(
            model_name='thansatbymonth',
            name='month_9',
        ),
        migrations.AlterField(
            model_name='thansatbymonth',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbyyear'),
        ),
        migrations.CreateModel(
            name='SaoMonth9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cung_son', models.IntegerField(choices=[(1, 'Cung'), (2, 'Son')])),
                ('direction', models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('than_sat_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbymonth')),
            ],
            options={
                'verbose_name': 'Sao',
                'verbose_name_plural': 'Sao',
            },
        ),
        migrations.CreateModel(
            name='SaoMonth8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cung_son', models.IntegerField(choices=[(1, 'Cung'), (2, 'Son')])),
                ('direction', models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('than_sat_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbymonth')),
            ],
            options={
                'verbose_name': 'Sao',
                'verbose_name_plural': 'Sao',
            },
        ),
        migrations.CreateModel(
            name='SaoMonth7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cung_son', models.IntegerField(choices=[(1, 'Cung'), (2, 'Son')])),
                ('direction', models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('than_sat_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbymonth')),
            ],
            options={
                'verbose_name': 'Sao',
                'verbose_name_plural': 'Sao',
            },
        ),
        migrations.CreateModel(
            name='SaoMonth6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cung_son', models.IntegerField(choices=[(1, 'Cung'), (2, 'Son')])),
                ('direction', models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('than_sat_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbymonth')),
            ],
            options={
                'verbose_name': 'Sao',
                'verbose_name_plural': 'Sao',
            },
        ),
        migrations.CreateModel(
            name='SaoMonth5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cung_son', models.IntegerField(choices=[(1, 'Cung'), (2, 'Son')])),
                ('direction', models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('than_sat_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbymonth')),
            ],
            options={
                'verbose_name': 'Sao',
                'verbose_name_plural': 'Sao',
            },
        ),
        migrations.CreateModel(
            name='SaoMonth4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cung_son', models.IntegerField(choices=[(1, 'Cung'), (2, 'Son')])),
                ('direction', models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('than_sat_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbymonth')),
            ],
            options={
                'verbose_name': 'Sao',
                'verbose_name_plural': 'Sao',
            },
        ),
        migrations.CreateModel(
            name='SaoMonth3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cung_son', models.IntegerField(choices=[(1, 'Cung'), (2, 'Son')])),
                ('direction', models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('than_sat_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbymonth')),
            ],
            options={
                'verbose_name': 'Sao',
                'verbose_name_plural': 'Sao',
            },
        ),
        migrations.CreateModel(
            name='SaoMonth2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cung_son', models.IntegerField(choices=[(1, 'Cung'), (2, 'Son')])),
                ('direction', models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('than_sat_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbymonth')),
            ],
            options={
                'verbose_name': 'Sao',
                'verbose_name_plural': 'Sao',
            },
        ),
        migrations.CreateModel(
            name='SaoMonth12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cung_son', models.IntegerField(choices=[(1, 'Cung'), (2, 'Son')])),
                ('direction', models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('than_sat_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbymonth')),
            ],
            options={
                'verbose_name': 'Sao',
                'verbose_name_plural': 'Sao',
            },
        ),
        migrations.CreateModel(
            name='SaoMonth11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cung_son', models.IntegerField(choices=[(1, 'Cung'), (2, 'Son')])),
                ('direction', models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('than_sat_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbymonth')),
            ],
            options={
                'verbose_name': 'Sao',
                'verbose_name_plural': 'Sao',
            },
        ),
        migrations.CreateModel(
            name='SaoMonth10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cung_son', models.IntegerField(choices=[(1, 'Cung'), (2, 'Son')])),
                ('direction', models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('than_sat_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbymonth')),
            ],
            options={
                'verbose_name': 'Sao',
                'verbose_name_plural': 'Sao',
            },
        ),
        migrations.CreateModel(
            name='SaoMonth1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cung_son', models.IntegerField(choices=[(1, 'Cung'), (2, 'Son')])),
                ('direction', models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255)),
                ('sao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.sao')),
                ('than_sat_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.thansatbymonth')),
            ],
            options={
                'verbose_name': 'Sao',
                'verbose_name_plural': 'Sao',
            },
        ),
        migrations.AddField(
            model_name='thansatbymonth',
            name='month_1',
            field=models.ManyToManyField(related_name='sao_month_1', through='apis.SaoMonth1', to='apis.Sao'),
        ),
        migrations.AddField(
            model_name='thansatbymonth',
            name='month_10',
            field=models.ManyToManyField(related_name='sao_month_10', through='apis.SaoMonth10', to='apis.Sao'),
        ),
        migrations.AddField(
            model_name='thansatbymonth',
            name='month_11',
            field=models.ManyToManyField(related_name='sao_month_11', through='apis.SaoMonth11', to='apis.Sao'),
        ),
        migrations.AddField(
            model_name='thansatbymonth',
            name='month_12',
            field=models.ManyToManyField(related_name='sao_month_12', through='apis.SaoMonth12', to='apis.Sao'),
        ),
        migrations.AddField(
            model_name='thansatbymonth',
            name='month_2',
            field=models.ManyToManyField(related_name='sao_month_2', through='apis.SaoMonth2', to='apis.Sao'),
        ),
        migrations.AddField(
            model_name='thansatbymonth',
            name='month_3',
            field=models.ManyToManyField(related_name='sao_month_3', through='apis.SaoMonth3', to='apis.Sao'),
        ),
        migrations.AddField(
            model_name='thansatbymonth',
            name='month_4',
            field=models.ManyToManyField(related_name='sao_month_4', through='apis.SaoMonth4', to='apis.Sao'),
        ),
        migrations.AddField(
            model_name='thansatbymonth',
            name='month_5',
            field=models.ManyToManyField(related_name='sao_month_5', through='apis.SaoMonth5', to='apis.Sao'),
        ),
        migrations.AddField(
            model_name='thansatbymonth',
            name='month_6',
            field=models.ManyToManyField(related_name='sao_month_6', through='apis.SaoMonth6', to='apis.Sao'),
        ),
        migrations.AddField(
            model_name='thansatbymonth',
            name='month_7',
            field=models.ManyToManyField(related_name='sao_month_7', through='apis.SaoMonth7', to='apis.Sao'),
        ),
        migrations.AddField(
            model_name='thansatbymonth',
            name='month_8',
            field=models.ManyToManyField(related_name='sao_month_8', through='apis.SaoMonth8', to='apis.Sao'),
        ),
        migrations.AddField(
            model_name='thansatbymonth',
            name='month_9',
            field=models.ManyToManyField(related_name='sao_month_9', through='apis.SaoMonth9', to='apis.Sao'),
        ),
    ]
