# Generated by Django 3.1 on 2023-04-19 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0038_auto_20230419_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saomonth1',
            options={'verbose_name': 'Sao tháng 1', 'verbose_name_plural': 'Sao tháng 1'},
        ),
        migrations.AlterModelOptions(
            name='saomonth10',
            options={'verbose_name': 'Sao tháng 10', 'verbose_name_plural': 'Sao tháng 10'},
        ),
        migrations.AlterModelOptions(
            name='saomonth11',
            options={'verbose_name': 'Sao tháng 11', 'verbose_name_plural': 'Sao tháng 11'},
        ),
        migrations.AlterModelOptions(
            name='saomonth12',
            options={'verbose_name': 'Sao tháng 12', 'verbose_name_plural': 'Sao tháng 12'},
        ),
        migrations.AlterModelOptions(
            name='saomonth2',
            options={'verbose_name': 'Sao tháng 2', 'verbose_name_plural': 'Sao tháng 2'},
        ),
        migrations.AlterModelOptions(
            name='saomonth3',
            options={'verbose_name': 'Sao tháng 3', 'verbose_name_plural': 'Sao tháng 3'},
        ),
        migrations.AlterModelOptions(
            name='saomonth4',
            options={'verbose_name': 'Sao tháng 4', 'verbose_name_plural': 'Sao tháng 4'},
        ),
        migrations.AlterModelOptions(
            name='saomonth5',
            options={'verbose_name': 'Sao tháng 5', 'verbose_name_plural': 'Sao tháng 5'},
        ),
        migrations.AlterModelOptions(
            name='saomonth6',
            options={'verbose_name': 'Sao tháng 6', 'verbose_name_plural': 'Sao tháng 6'},
        ),
        migrations.AlterModelOptions(
            name='saomonth7',
            options={'verbose_name': 'Sao tháng 7', 'verbose_name_plural': 'Sao tháng 7'},
        ),
        migrations.AlterModelOptions(
            name='saomonth8',
            options={'verbose_name': 'Sao tháng 8', 'verbose_name_plural': 'Sao tháng 8'},
        ),
        migrations.AlterModelOptions(
            name='saomonth9',
            options={'verbose_name': 'Sao tháng 9', 'verbose_name_plural': 'Sao tháng 9'},
        ),
    ]
