# Generated by Django 3.1 on 2023-04-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0041_auto_20230419_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saomonth1',
            name='direction',
            field=models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Quý', 'Quý'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255, verbose_name='Phương hướng'),
        ),
        migrations.AlterField(
            model_name='saomonth10',
            name='direction',
            field=models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Quý', 'Quý'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255, verbose_name='Phương hướng'),
        ),
        migrations.AlterField(
            model_name='saomonth11',
            name='direction',
            field=models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Quý', 'Quý'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255, verbose_name='Phương hướng'),
        ),
        migrations.AlterField(
            model_name='saomonth12',
            name='direction',
            field=models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Quý', 'Quý'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255, verbose_name='Phương hướng'),
        ),
        migrations.AlterField(
            model_name='saomonth2',
            name='direction',
            field=models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Quý', 'Quý'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255, verbose_name='Phương hướng'),
        ),
        migrations.AlterField(
            model_name='saomonth3',
            name='direction',
            field=models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Quý', 'Quý'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255, verbose_name='Phương hướng'),
        ),
        migrations.AlterField(
            model_name='saomonth4',
            name='direction',
            field=models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Quý', 'Quý'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255, verbose_name='Phương hướng'),
        ),
        migrations.AlterField(
            model_name='saomonth5',
            name='direction',
            field=models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Quý', 'Quý'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255, verbose_name='Phương hướng'),
        ),
        migrations.AlterField(
            model_name='saomonth6',
            name='direction',
            field=models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Quý', 'Quý'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255, verbose_name='Phương hướng'),
        ),
        migrations.AlterField(
            model_name='saomonth7',
            name='direction',
            field=models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Quý', 'Quý'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255, verbose_name='Phương hướng'),
        ),
        migrations.AlterField(
            model_name='saomonth8',
            name='direction',
            field=models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Quý', 'Quý'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255, verbose_name='Phương hướng'),
        ),
        migrations.AlterField(
            model_name='saomonth9',
            name='direction',
            field=models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Quý', 'Quý'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255, verbose_name='Phương hướng'),
        ),
        migrations.AlterField(
            model_name='thansatbyyearsao',
            name='direction',
            field=models.CharField(choices=[('Khảm', 'Khảm'), ('Cấn', 'Cấn'), ('Chấn', 'Chấn'), ('Tốn', 'Tốn'), ('Ly', 'Ly'), ('Khôn', 'Khôn'), ('Đoài', 'Đoài'), ('Càn', 'Càn'), ('Nhâm', 'Nhâm'), ('Quý', 'Quý'), ('Tý', 'Tý'), ('Sửu', 'Sửu'), ('Dần', 'Dần'), ('Giáp', 'Giáp'), ('Mão', 'Mão'), ('Ất', 'Ất'), ('Thìn', 'Thìn'), ('Tốn', 'Tốn'), ('Tỵ', 'Tỵ'), ('Bính', 'Bính'), ('Ngọ', 'Ngọ'), ('Đinh', 'Đinh'), ('Mùi', 'Mùi'), ('Khôn', 'Khôn'), ('Thân', 'Thân'), ('Canh', 'Canh'), ('Dậu', 'Dậu'), ('Tân', 'Tân'), ('Tuất', 'Tuất'), ('Hợi', 'Hợi')], max_length=255, verbose_name='Phương hướng'),
        ),
    ]
