# Generated by Django 3.1 on 2023-05-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0043_auto_20230421_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=255)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lịch đặt',
                'verbose_name_plural': 'Lịch đặt',
            },
        ),
    ]
