# Generated by Django 3.1 on 2023-05-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0048_auto_20230509_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
