# Generated by Django 3.1 on 2023-05-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0049_auto_20230509_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
