# Generated by Django 3.1 on 2023-05-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0050_auto_20230509_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('very_good_from', models.FloatField(verbose_name='Ngày rất tốt từ')),
                ('very_good_to', models.FloatField(verbose_name='Ngày rất tốt đến')),
                ('good_from', models.FloatField(verbose_name='Ngày tốt từ')),
                ('good_to', models.FloatField(verbose_name='Ngày tốt đến')),
                ('ugly_from', models.FloatField(verbose_name='Ngày xấu từ')),
                ('to_from', models.FloatField(verbose_name='Ngày xấu đến')),
            ],
            options={
                'verbose_name': 'Cài đặt ngày tốt xấu',
                'verbose_name_plural': 'Cài đặt ngày tốt xấu',
            },
        ),
        migrations.CreateModel(
            name='HoursConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('very_good', models.FloatField(verbose_name='Giờ rất tốt')),
                ('good', models.FloatField(verbose_name='Giờ tốt')),
            ],
            options={
                'verbose_name': 'Cài đặt giờ tốt xấu',
                'verbose_name_plural': 'Cài đặt giờ tốt xấu',
            },
        ),
    ]
