# Generated by Django 3.1 on 2023-05-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0051_dateconfig_hoursconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateconfig',
            old_name='to_from',
            new_name='ugly_to',
        ),
    ]
