# Generated by Django 3.1 on 2023-05-18 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0052_auto_20230518_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateconfig',
            name='very_good_to',
        ),
    ]
