# Generated by Django 3.1 on 2023-05-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0053_remove_dateconfig_very_good_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateconfig',
            name='good_to',
        ),
        migrations.RemoveField(
            model_name='dateconfig',
            name='ugly_to',
        ),
        migrations.AlterField(
            model_name='dateconfig',
            name='good_from',
            field=models.FloatField(verbose_name='Ngày tốt'),
        ),
        migrations.AlterField(
            model_name='dateconfig',
            name='ugly_from',
            field=models.FloatField(verbose_name='Ngày xấu'),
        ),
        migrations.AlterField(
            model_name='dateconfig',
            name='very_good_from',
            field=models.FloatField(verbose_name='Ngày rất tốt'),
        ),
    ]
