# Generated by Django 3.1 on 2023-05-21 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0054_auto_20230518_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255, verbose_name='Số tài khoản')),
                ('account_holder', models.CharField(max_length=255, verbose_name='Chủ tài khoản')),
                ('bank', models.CharField(max_length=255, verbose_name='Ngân hàng')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chi nhánh')),
            ],
            options={
                'verbose_name': 'Ngân hàng',
                'verbose_name_plural': 'Ngân hàng',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.IntegerField(default=0, verbose_name='Thành viên trả phí')),
                ('expiry_datetime', models.DateField(null=True, verbose_name='Thời gian hết hạn')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='code')),
                ('status', models.IntegerField(default=0, verbose_name='Trạng thái')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chi nhánh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ngân hàng',
                'verbose_name_plural': 'Ngân hàng',
            },
        ),
    ]
