# Generated by Django 3.1 on 2023-05-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0055_bankconfig_banktransaction_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'verbose_name': 'Giao dịch', 'verbose_name_plural': 'Giao dịch'},
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='branch',
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'Tạo mới'), (0, 'Hoàn thành')], default=0, verbose_name='Trạng thái'),
        ),
    ]
