# Generated by Django 3.1.14 on 2023-05-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0056_auto_20230521_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'Tạo mới'), (1, 'Hoàn thành')], default=0, verbose_name='Trạng thái'),
        ),
    ]
