# Generated by Django 3.1 on 2023-05-29 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0059_hoursconfig_ugly'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên hệ sao')),
            ],
            options={
                'verbose_name': 'Hệ sao',
                'verbose_name_plural': 'Hệ sao',
            },
        ),
        migrations.AddField(
            model_name='sao',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.categorystars'),
        ),
    ]
