# Generated by Django 3.1 on 2023-06-17 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0060_auto_20230529_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdate',
            name='before_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sao',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.categorystars', verbose_name='Hệ sao'),
        ),
    ]
