# Generated by Django 3.1 on 2023-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0061_auto_20230617_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankconfig',
            name='qr_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QR'),
        ),
    ]
