# Generated by Django 3.1.14 on 2023-06-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0063_auto_20230619_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='sao',
            name='calendar',
            field=models.IntegerField(blank=True, choices=[(1, 'Âm lịch'), (2, 'Tiết khí')], null=True, verbose_name='Chạy theo'),
        ),
        migrations.AddField(
            model_name='sao',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Tháng'),
        ),
    ]
