# Generated by Django 3.1.14 on 2023-06-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0064_auto_20230628_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sao',
            name='month',
        ),
    ]
