# Generated by Django 3.1.14 on 2023-07-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0065_remove_sao_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='sao',
            name='level',
            field=models.FloatField(blank=True, null=True, verbose_name='Cập độ'),
        ),
        migrations.AddField(
            model_name='sao',
            name='point',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm'),
        ),
    ]
