# Generated by Django 3.1.14 on 2023-07-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0067_auto_20230707_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saomonth1',
            name='cung_son',
            field=models.IntegerField(blank=True, choices=[(1, 'Cung'), (2, 'Son')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='saomonth10',
            name='cung_son',
            field=models.IntegerField(blank=True, choices=[(1, 'Cung'), (2, 'Son')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='saomonth11',
            name='cung_son',
            field=models.IntegerField(blank=True, choices=[(1, 'Cung'), (2, 'Son')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='saomonth12',
            name='cung_son',
            field=models.IntegerField(blank=True, choices=[(1, 'Cung'), (2, 'Son')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='saomonth2',
            name='cung_son',
            field=models.IntegerField(blank=True, choices=[(1, 'Cung'), (2, 'Son')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='saomonth3',
            name='cung_son',
            field=models.IntegerField(blank=True, choices=[(1, 'Cung'), (2, 'Son')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='saomonth4',
            name='cung_son',
            field=models.IntegerField(blank=True, choices=[(1, 'Cung'), (2, 'Son')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='saomonth5',
            name='cung_son',
            field=models.IntegerField(blank=True, choices=[(1, 'Cung'), (2, 'Son')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='saomonth6',
            name='cung_son',
            field=models.IntegerField(blank=True, choices=[(1, 'Cung'), (2, 'Son')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='saomonth7',
            name='cung_son',
            field=models.IntegerField(blank=True, choices=[(1, 'Cung'), (2, 'Son')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='saomonth8',
            name='cung_son',
            field=models.IntegerField(blank=True, choices=[(1, 'Cung'), (2, 'Son')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='saomonth9',
            name='cung_son',
            field=models.IntegerField(blank=True, choices=[(1, 'Cung'), (2, 'Son')], editable=False, null=True),
        ),
    ]
