# Generated by Django 3.1.14 on 2023-07-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0068_auto_20230707_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sao',
            name='level',
        ),
        migrations.AddField(
            model_name='sao',
            name='level_day',
            field=models.FloatField(blank=True, null=True, verbose_name='Cấp độ theo ngày'),
        ),
        migrations.AddField(
            model_name='sao',
            name='level_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Cấp độ theo giờ'),
        ),
        migrations.AddField(
            model_name='sao',
            name='level_month',
            field=models.FloatField(blank=True, null=True, verbose_name='Cấp độ theo tháng'),
        ),
        migrations.AddField(
            model_name='sao',
            name='level_year',
            field=models.FloatField(blank=True, null=True, verbose_name='Cấp độ theo năm'),
        ),
    ]
