# Generated by Django 3.1.14 on 2023-07-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0069_auto_20230710_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='sao',
            name='level',
            field=models.FloatField(blank=True, null=True, verbose_name='Cấp độ'),
        ),
    ]
