# Generated by Django 3.1 on 2026-09-05 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0071_directionconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdate',
            name='before_days',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddIndex(
            model_name='quynhan',
            index=models.Index(fields=['can_ngay'], name='quy_nhan_can_ngay_idx'),
        ),
        migrations.AddIndex(
            model_name='tietkhi',
            index=models.Index(fields=['start_time'], name='tiet_khi_start_idx'),
        ),
        migrations.AddIndex(
            model_name='tietkhi',
            index=models.Index(fields=['tiet_khi', 'start_time'], name='tiet_khi_name_start_idx'),
        ),
        migrations.AddIndex(
            model_name='tudaicatthoi',
            index=models.Index(fields=['can_ngay'], name='tu_dai_can_ngay_idx'),
        ),
    ]
